name: hikami_sushi
description: "Hikimi sushi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: 6.1.0
  dropdown_button2: ^2.3.9

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/dessert/
    - assets/images/drinks/
    - assets/images/logo/
    - assets/images/fried_item/
    - assets/images/grill/
    - assets/images/hotpot/
    - assets/images/otsumami/
    - assets/images/rice/
    - assets/images/salad/
    - assets/images/sashimi/
    - assets/images/shusi/
    - assets/images/soup/
    - assets/images/wine/
    - assets/images/noodles/
    - assets/images/itame/
    - assets/images/okonomi_yaki/
    - assets/images/lunchMenu/



    
    